source 'https://rubygems.org'
ruby '2.5.1'
gem 'colorize'
gem 'csv'
gem 'date'
gem 'dotenv'
gem 'google_drive'
gem 'json'
gem 'launchy'
gem 'nokogiri'
gem 'pry'
gem 'rspec'
gem 'rubocop', '~> 0.57.2'
gem 'tty-prompt'
gem 'watir'
